/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso1`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso2`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso3`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso4`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso5`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso6`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso7`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso1_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso2_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso3_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso4_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso5_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso6_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso7_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/useEstadoEvento_mp`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useConexionSimulada`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Paso1`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Paso2`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Paso3`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Paso4`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Paso5`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Paso6`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Paso7`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/Paso1_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/Paso2_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/Paso3_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/Paso4_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/Paso5_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/Paso6_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/Paso7_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/ejercicios_mp/useEstadoEvento_mp`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useConexionSimulada`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Paso1${`?${string}` | `#${string}` | ''}` | `/components/Paso2${`?${string}` | `#${string}` | ''}` | `/components/Paso3${`?${string}` | `#${string}` | ''}` | `/components/Paso4${`?${string}` | `#${string}` | ''}` | `/components/Paso5${`?${string}` | `#${string}` | ''}` | `/components/Paso6${`?${string}` | `#${string}` | ''}` | `/components/Paso7${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/Paso1_mp${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/Paso2_mp${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/Paso3_mp${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/Paso4_mp${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/Paso5_mp${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/Paso6_mp${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/Paso7_mp${`?${string}` | `#${string}` | ''}` | `/ejercicios_mp/useEstadoEvento_mp${`?${string}` | `#${string}` | ''}` | `/hooks/useConexionSimulada${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso1`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso2`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso3`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso4`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso5`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso6`; params?: Router.UnknownInputParams; } | { pathname: `/components/Paso7`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso1_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso2_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso3_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso4_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso5_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso6_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/Paso7_mp`; params?: Router.UnknownInputParams; } | { pathname: `/ejercicios_mp/useEstadoEvento_mp`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useConexionSimulada`; params?: Router.UnknownInputParams; };
    }
  }
}
